set(OS "android")
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CPU "arm64-v8a")
set(PLATFORM "")
set(APP_RENDER_SYSTEM )

set(CMAKE_FIND_ROOT_PATH @CMAKE_FIND_ROOT_PATH@)

# set CORE_SYSTEM_NAME and CMAKE_SYSTEM_NAME (sets CMAKE_CROSSCOMPILING)
if(OS STREQUAL linux)
  set(CMAKE_SYSTEM_NAME Linux)
  set(CORE_SYSTEM_NAME linux)
  set(CORE_PLATFORM_NAME )
  if(NOT APP_RENDER_SYSTEM)
    set(APP_RENDER_SYSTEM gl)
  endif()
elseif(OS STREQUAL android)
  set(CMAKE_SYSTEM_NAME Android)
  set(CORE_SYSTEM_NAME android)
  if(NOT APP_RENDER_SYSTEM)
    set(APP_RENDER_SYSTEM gles)
  endif()
elseif(OS STREQUAL osx)
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CORE_SYSTEM_NAME osx)
  if(NOT APP_RENDER_SYSTEM)
    set(APP_RENDER_SYSTEM gl)
  endif()
elseif(OS STREQUAL darwin_embedded)
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CORE_SYSTEM_NAME darwin_embedded)
  if(PLATFORM STREQUAL appletvos)
    set(CORE_PLATFORM_NAME tvos)
  else()
    set(CORE_PLATFORM_NAME ios)
  endif()
  if(NOT APP_RENDER_SYSTEM)
    set(APP_RENDER_SYSTEM gles)
  endif()
endif()

if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
  set(CMAKE_OSX_SYSROOT /home/sven/android-tools/android-sdk-linux)
  set(CMAKE_LIBRARY_PATH ${CMAKE_FIND_ROOT_PATH}/lib:/home/sven/android-tools/android-sdk-linux/lib:/usr/X11R6/lib)
  set(CMAKE_INCLUDE_PATH ${CMAKE_FIND_ROOT_PATH}/include:/home/sven/android-tools/android-sdk-linux/include:/usr/X11R6/include)
  list(APPEND CMAKE_FIND_ROOT_PATH ${CMAKE_OSX_SYSROOT} ${CMAKE_OSX_SYSROOT}/usr /usr/X11R6)
endif()
set(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
set(CMAKE_C_COMPILER /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang)
set(CMAKE_CXX_COMPILER /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++)
set(CMAKE_AR /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar CACHE FILEPATH "Archiver")
set(CMAKE_LINKER /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/ld CACHE FILEPATH "Linker")
set(CMAKE_NM /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm CACHE FILEPATH "Nm")
set(CMAKE_OBJDUMP /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-objdump CACHE FILEPATH "Objdump")
set(CMAKE_RANLIB /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib CACHE FILEPATH "Ranlib")

if(NOT "yes" STREQUAL "")
  set(CMAKE_CXX_COMPILER_LAUNCHER /usr/bin/ccache)
  set(CMAKE_C_COMPILER_LAUNCHER /usr/bin/ccache)
endif()

# where is the target environment
if(NOT "/home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64" STREQUAL "")
  if("" STREQUAL "webos")
    list(APPEND CMAKE_FIND_ROOT_PATH /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/aarch64-linux-android/sysroot)
  else()
    list(APPEND CMAKE_FIND_ROOT_PATH /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr)
  endif()
endif()

# add Android directories and tools
if(CORE_SYSTEM_NAME STREQUAL android)
  set(NDKROOT /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358)
  set(SDKROOT /home/sven/android-tools/android-sdk-linux)
  set(TOOLCHAIN /home/sven/android-tools/android-sdk-linux/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64)
  set(HOST aarch64-linux-android)
  list(APPEND CMAKE_LIBRARY_PATH ${TOOLCHAIN}/sysroot/usr/lib/${HOST}/21)
  string(REPLACE ":" ";" SDK_BUILDTOOLS_PATH "/home/sven/android-tools/android-sdk-linux/tools:/home/sven/android-tools/android-sdk-linux/platform-tools:/home/sven/android-tools/android-sdk-linux/build-tools/37.0.0")
endif()

set(CMAKE_C_FLAGS "-DANDROID -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -mtune=cortex-a53 -Og -g -D_DEBUG  -isystem /home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/include/android-21")
set(CMAKE_CXX_FLAGS "-DANDROID -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -mtune=cortex-a53 -frtti -Og -g -D_DEBUG  -std=c++17 -isystem /home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/include/android-21")
set(CMAKE_C_FLAGS_RELEASE "-DANDROID -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -mtune=cortex-a53 -DNDEBUG=1 -Os  -isystem /home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/include/android-21")
set(CMAKE_CXX_FLAGS_RELEASE "-DANDROID -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -mtune=cortex-a53 -frtti -DNDEBUG=1 -Os  -isystem /home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/include/android-21")
set(CMAKE_C_FLAGS_DEBUG "-DANDROID -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -mtune=cortex-a53 -Og -g -D_DEBUG  -isystem /home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/include/android-21")
set(CMAKE_CXX_FLAGS_DEBUG "-DANDROID -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -mtune=cortex-a53 -frtti -Og -g -D_DEBUG  -isystem /home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/include/android-21")
set(CMAKE_CPP_FLAGS "-DANDROID -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -mtune=cortex-a53 -Og -g -D_DEBUG  -isystem /home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/include/android-21")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -L/home/sven/easytv-64/xbmc-depends/aarch64-linux-android-21-debug/lib/android-21  ")
set(ENV{CFLAGS} ${CMAKE_C_FLAGS})
set(ENV{CXXFLAGS} ${CMAKE_CXX_FLAGS})
set(ENV{CPPFLAGS} ${CMAKE_CPP_FLAGS})
set(ENV{LDFLAGS} ${CMAKE_EXE_LINKER_FLAGS})
# search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_FRAMEWORK LAST)

# Binary Addons
if(NOT CORE_SYSTEM_NAME STREQUAL linux)
  set(ADDONS_PREFER_STATIC_LIBS ON)
endif()

set(KODI_DEPENDSBUILD 1)

